import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
test('canonical migration compiles and Search/Hire/quota share real Postgres boundaries',async()=>{
 const db=new PGlite();
 try{
  const prior=readFileSync('_shared/structured-retrieval.test.ts','utf8');
  const setup=prior.slice(prior.indexOf('await db.exec(`')+15,prior.indexOf('`);'));
  await db.exec(setup);
  await db.exec(`create schema auth;
   create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
   create table public.profiles(id uuid primary key);
   create function public.current_profile_id() returns uuid language sql as $$select auth.uid()$$;
   create function private.community_account_active(uuid) returns boolean language sql as $$select $1 is not null$$;
   create table neighborhoods(id uuid,name text,city text);
   create table neighborhood_memberships(profile_id uuid,neighborhood_id uuid,is_primary boolean);
   create function public.has_verified_neighborhood_membership(uuid) returns boolean language sql as $$select exists(select 1 from public.neighborhood_memberships where profile_id=auth.uid() and neighborhood_id=$1)$$;
   alter table provider_profiles add column general_area text,add column rating numeric,add column review_count integer,add column completed_jobs integer,add column response_rate integer,add column community_recommendations integer;
   insert into profiles values('97000000-0000-4000-8000-000000000001');
   insert into neighborhoods values('97000000-0000-4000-8000-000000000090','Fixture','Accra');
   insert into neighborhood_memberships values('97000000-0000-4000-8000-000000000001','97000000-0000-4000-8000-000000000090',true);
   set request.jwt.claim.sub='97000000-0000-4000-8000-000000000001';
   update feature_flags set enabled=false;
   insert into feature_flags values('ai_neighborhood_assistant',true);`);
  const base=readFileSync('../migrations/20260925032118_ai_neighborhood_retrieval.sql','utf8');
  await db.exec(base.slice(base.indexOf('create table private.neighborhood_ai_usage'),base.indexOf('-- Private helper')));
  const keyword=readFileSync('../migrations/20260926003542_keyword_discovery.sql','utf8');
  await db.exec(keyword.slice(0,keyword.indexOf('create or replace function public.neighborhood_ai_search'))+'commit;');
  await db.exec(readFileSync('../migrations/20260927040151_assistant_structured_retrieval.sql','utf8'));
  await db.exec(readFileSync('../migrations/20260928213631_canonical_neighborhood_search.sql','utf8'));
  await db.exec(`insert into provider_profiles(id,business_name,headline,accepting_requests) select ('97000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'Fixture '||n,'Plumbing',true from generate_series(11,13)n;
   insert into provider_services select id,'Plumbing','plumbing' from provider_profiles;
   insert into provider_service_areas select id,'97000000-0000-4000-8000-000000000090' from provider_profiles where id::text not like '%013';`);
  const result=async(sql:string)=>(await db.query<{data:any}>(`select ${sql} data`)).rows[0].data;
  const search=await result(`neighborhood_search_retrieve('provider','plumber',null,null,null,'{"categories":["plumbing"]}')`);
  const hire=await result(`neighborhood_provider_catalog('plumbing')`);
  assert.equal(search.length,2);assert.deepEqual(search.map((x:any)=>x.id),hire.map((x:any)=>x.id));
  assert.equal((await result(`neighborhood_ai_quota_status()`)).used,0);
  await db.exec(`insert into private.neighborhood_ai_usage(profile_id,day_at,day_count,minute_at,minute_count) values(auth.uid(),(now() at time zone 'UTC')::date,32,now()-interval '2 minutes',0)`);
  const q=await result('neighborhood_ai_quota_status()');assert.equal(q.percent,80);assert.equal(q.remaining,8);assert.equal(q.window_type,'calendar_day_utc');
  assert.equal((await result(`private.neighborhood_ai_meter('start',null,'{}')`)).quota.used,33);
  await db.exec('update private.neighborhood_ai_usage set day_count=40');
  await assert.rejects(result(`private.neighborhood_ai_meter('start',null,'{}')`),(e:any)=>e.code==='54000'&&JSON.parse(e.detail).blocked_scope==='account_daily');
  assert.equal((await result(`neighborhood_provider_catalog('plumbing')`)).length,2);
  const reset=await result(`private.neighborhood_ai_quota((date_trunc('day',now() at time zone 'UTC') at time zone 'UTC')+interval '1 day')`);assert.equal(reset.used,0);
  await db.exec(`update private.neighborhood_ai_usage set day_at=(now() at time zone 'UTC')::date-1,minute_count=0,minute_at=now()-interval '2 minutes'`);
  assert.equal((await result('neighborhood_ai_quota_status()')).used,0);
  assert.equal((await result(`private.neighborhood_ai_meter('start',null,'{}')`)).quota.used,1);
  await db.exec(`update private.neighborhood_ai_usage set minute_count=6,minute_at=now()`);
  assert.equal((await result('neighborhood_ai_quota_status()')).blocked_scope,'account_minute');
  await assert.rejects(result(`private.neighborhood_ai_meter('start',null,'{}')`));
  assert.equal(await result(`has_function_privilege('authenticated','private.neighborhood_ai_quota(timestamptz)','execute')`),false);
  assert.equal(await result(`has_function_privilege('anon','public.neighborhood_search_retrieve(text,text,uuid,timestamptz,timestamptz,jsonb)','execute')`),false);
 }finally{await db.close();}
});
