import type { JobRequest, JobRequestDraftInput, Provider, ServiceCategory } from '@/types/contracts';

export const categories: ServiceCategory[] = [
  { id: 'plumbing', name: 'Plumbing', icon: 'Pl', description: 'Leaks, pipes, fittings, drainage' },
  { id: 'electrical', name: 'Electrical', icon: 'El', description: 'Power faults, sockets, lighting' },
  { id: 'cleaning', name: 'Cleaning', icon: 'Cl', description: 'Home, office, move-in, deep cleaning' },
  { id: 'carpentry', name: 'Carpentry', icon: 'Ca', description: 'Doors, shelves, cabinets, repairs' },
  {
    id: 'air-conditioning',
    name: 'Air conditioning and refrigeration',
    icon: 'AC',
    description: 'AC servicing, cooling faults, fridge support',
  },
  { id: 'appliance-repair', name: 'Appliance repair', icon: 'Ap', description: 'Washers, cookers, small appliances' },
  {
    id: 'moving-delivery',
    name: 'Moving and delivery',
    icon: 'Mv',
    description: 'Small moves, delivery, loading help',
  },
  { id: 'painting', name: 'Painting', icon: 'Pa', description: 'Interior and exterior painting' },
];

function signals(
  provider: Pick<Provider, 'phoneVerified' | 'completedJobs' | 'responseRate' | 'communityRecommendations'>,
) {
  return [
    { id: 'phone', label: 'Phone verified', value: provider.phoneVerified ? 'Yes' : 'No' },
    { id: 'jobs', label: 'Completed jobs', value: String(provider.completedJobs) },
    { id: 'response', label: 'Response rate', value: provider.responseRate },
    { id: 'recommendations', label: 'Community recommendations', value: String(provider.communityRecommendations) },
  ];
}

const providerSeed: Omit<Provider, 'trustSignals'>[] = [
  {
    id: 'prov-01',
    name: 'Kwame PipeCare',
    headline: 'Fast home plumbing support',
    serviceLabel: 'Plumbing',
    neighborhood: 'East Legon',
    areaLabel: 'East Legon and nearby',
    categoryIds: ['plumbing'],
    imageKind: 'initials',
    rating: 4.8,
    reviewCount: 37,
    communityRecommendations: 18,
    phoneVerified: true,
    availability: 'Available today after 3:00 PM',
    completedJobs: 46,
    responseRate: '92%',
    accountAge: '2 years',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-02',
    name: 'Ama Spark Works',
    headline: 'Careful electrical repairs for homes and shops',
    serviceLabel: 'Electrical',
    neighborhood: 'Osu',
    areaLabel: 'Osu and Labone',
    categoryIds: ['electrical'],
    imageKind: 'initials',
    rating: 4.7,
    reviewCount: 29,
    communityRecommendations: 12,
    phoneVerified: true,
    availability: 'Usually responds within 1 hour',
    completedJobs: 32,
    responseRate: '89%',
    accountAge: '18 months',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-03',
    name: 'BrightClean Ghana',
    headline: 'Reliable home and office cleaning team',
    serviceLabel: 'Cleaning',
    neighborhood: 'Labone',
    areaLabel: 'Labone and Cantonments',
    categoryIds: ['cleaning'],
    imageKind: 'illustration',
    rating: 4.9,
    reviewCount: 44,
    communityRecommendations: 21,
    phoneVerified: true,
    availability: 'Available tomorrow morning',
    completedJobs: 58,
    responseRate: '95%',
    accountAge: '3 years',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-04',
    name: 'Kojo Wood & Fit',
    headline: 'Door, shelf, and cabinet repairs',
    serviceLabel: 'Carpentry',
    neighborhood: 'Madina',
    areaLabel: 'Madina and Adenta',
    categoryIds: ['carpentry'],
    imageKind: 'initials',
    rating: 4.6,
    reviewCount: 18,
    communityRecommendations: 9,
    phoneVerified: true,
    availability: 'Available this week',
    completedJobs: 25,
    responseRate: '84%',
    accountAge: '2 years',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-05',
    name: 'Naa HomeFix',
    headline: 'Small household repairs and quick fixes',
    serviceLabel: 'Plumbing and electrical',
    neighborhood: 'Adenta',
    areaLabel: 'Adenta and Madina',
    categoryIds: ['plumbing', 'electrical'],
    imageKind: 'initials',
    rating: 4.5,
    reviewCount: 16,
    communityRecommendations: 8,
    phoneVerified: true,
    availability: 'Available Saturday',
    completedJobs: 19,
    responseRate: '80%',
    accountAge: '1 year',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-06',
    name: 'CoolAir Tema',
    headline: 'AC and refrigeration servicing',
    serviceLabel: 'Air conditioning and refrigeration',
    neighborhood: 'Tema Community 25',
    areaLabel: 'Tema Community 25 and Spintex',
    categoryIds: ['air-conditioning'],
    imageKind: 'illustration',
    rating: 4.8,
    reviewCount: 31,
    communityRecommendations: 13,
    phoneVerified: true,
    availability: 'Available today',
    completedJobs: 40,
    responseRate: '90%',
    accountAge: '2 years',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-07',
    name: 'FreshNest Cleaners',
    headline: 'Apartment and office cleaning',
    serviceLabel: 'Cleaning',
    neighborhood: 'Cantonments',
    areaLabel: 'Cantonments and Airport Residential',
    categoryIds: ['cleaning'],
    imageKind: 'initials',
    rating: 4.8,
    reviewCount: 39,
    communityRecommendations: 17,
    phoneVerified: true,
    availability: 'Available weekdays',
    completedJobs: 51,
    responseRate: '93%',
    accountAge: '30 months',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-08',
    name: 'Reliable Brush Co.',
    headline: 'Neat finishing and repainting',
    serviceLabel: 'Painting',
    neighborhood: 'Airport Residential',
    areaLabel: 'Airport Residential and Cantonments',
    categoryIds: ['painting'],
    imageKind: 'illustration',
    rating: 4.7,
    reviewCount: 27,
    communityRecommendations: 10,
    phoneVerified: true,
    availability: 'Available this week',
    completedJobs: 36,
    responseRate: '88%',
    accountAge: '20 months',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-09',
    name: 'Afi Pipe & Drain',
    headline: 'Leak and drain support',
    serviceLabel: 'Plumbing',
    neighborhood: 'Spintex',
    areaLabel: 'Spintex and Tema border',
    categoryIds: ['plumbing'],
    imageKind: 'initials',
    rating: 4.6,
    reviewCount: 22,
    communityRecommendations: 7,
    phoneVerified: true,
    availability: 'Usually responds same day',
    completedJobs: 28,
    responseRate: '87%',
    accountAge: '18 months',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-10',
    name: 'TidySpace Crew',
    headline: 'Move-in and deep cleaning',
    serviceLabel: 'Cleaning',
    neighborhood: 'Dzorwulu',
    areaLabel: 'Dzorwulu and Achimota',
    categoryIds: ['cleaning'],
    imageKind: 'illustration',
    rating: 4.8,
    reviewCount: 34,
    communityRecommendations: 15,
    phoneVerified: true,
    availability: 'Available tomorrow',
    completedJobs: 44,
    responseRate: '91%',
    accountAge: '2 years',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-11',
    name: 'Eben Appliance Assist',
    headline: 'Washer, cooker, and small appliance repair',
    serviceLabel: 'Appliance repair',
    neighborhood: 'Dansoman',
    areaLabel: 'Dansoman and Kaneshie',
    categoryIds: ['appliance-repair'],
    imageKind: 'initials',
    rating: 4.5,
    reviewCount: 15,
    communityRecommendations: 6,
    phoneVerified: true,
    availability: 'Available in 2 days',
    completedJobs: 21,
    responseRate: '85%',
    accountAge: '14 months',
    isAcceptingRequests: true,
  },
  {
    id: 'prov-12',
    name: 'SwiftMove Accra',
    headline: 'Small moves and delivery help',
    serviceLabel: 'Moving and delivery',
    neighborhood: 'Achimota',
    areaLabel: 'Achimota and Dzorwulu',
    categoryIds: ['moving-delivery'],
    imageKind: 'illustration',
    rating: 4.7,
    reviewCount: 24,
    communityRecommendations: 11,
    phoneVerified: true,
    availability: 'Available today before 6:00 PM',
    completedJobs: 30,
    responseRate: '86%',
    accountAge: '16 months',
    isAcceptingRequests: true,
  },
];

export const providers: Provider[] = providerSeed.map((provider) => ({
  ...provider,
  trustSignals: signals(provider),
}));

function buildInitialRequest(input: JobRequestDraftInput): JobRequest {
  const now = new Date().toISOString();
  return {
    ...input,
    id: 'req-100',
    status: 'Submitted',
    moderationStatus: 'not_run',
    createdAt: now,
    providerMessage: undefined,
    statusTimeline: [
      {
        id: 'evt-100',
        status: 'Submitted',
        actor: 'requester',
        createdAt: now,
      },
    ],
  };
}

export let requests: JobRequest[] = [
  buildInitialRequest({
    requesterName: 'Akosua Mensah',
    providerId: 'prov-01',
    categoryId: 'plumbing',
    neighborhood: 'East Legon',
    areaLabel: 'East Legon, near Lagos Avenue',
    title: 'Kitchen sink leak',
    description: 'My kitchen sink has been leaking since yesterday evening. I need help this week.',
    originalUserText: 'Kitchen sink is leaking badly since yesterday. I need someone this week.',
    urgency: 'soon',
    preferredDate: '2026-07-18',
    preferredTime: 'Weekday afternoon',
    contactPreference: 'app_update',
    photoCount: 1,
  }),
];
